. ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
. บ  COMMON.INC    Include file for TDS Common Area Definitions                บ
. บ  V.M=1.2     9/07/90                                                       บ
. บ                                                                            บ
. ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
.
ErrorMsg DIM       *12
Today    DIM       *8
Security FORM      *1
LogonID  DIM       *9
PortN    DIM       *2
ProcN    DIM       *1
VerFlag  DIM       *1
.
.   End of COMMON.INC   อออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
