. ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
. บ                                                                            บ
. บ    LC2UC.INC       26 July 90                                              บ
. บ                                                                            บ
. บ        Lower case to Upper Case translation table                          บ
. บ                                                                            บ
LC2UC    INIT   "aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ":        บ
                0x00,0x20                                                      บ
. บ                                                                            บ
. บ                                                                            บ
. ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
